# ADD VOIVODESHIPS

# LOCALHOST
POST http://localhost:8084/importer/voivodeships
Content-Type: application/json

{
  "voivodeships": [
    {
      "name": "PODKARPACKIE"
    },
    {
      "name": "MAŁOPOLSKIE"
    }
  ]
}

###

# MICROSERVICES
POST http://{eureka-server-address}:8084/importer/voivodeships
Content-Type: application/json

{
  "voivodeships": [
    {
      "name": "PODKARPACKIE"
    },
    {
      "name": "MAŁOPOLSKIE"
    }
  ]
}

###

# ADD COUNTIES

# LOCALHOST
POST http://localhost:8084/importer/counties/{voivodeshipName}
Content-Type: application/json

{
  "counties": [
    {
      "name": "STALOWOWOLSKI"
    },
    {
      "name": "NIŻAŃSKI"
    }
  ]
}

###

# MICROSERVICES
POST http://{eureka-server-address}:8084/importer/counties/{voivodeshipName}
Content-Type: application/json

{
  "counties": [
    {
      "name": "STALOWOWOLSKI"
    },
    {
      "name": "NIŻAŃSKI"
    }
  ]
}

###

# ADD LOCALITIES

# LOCALHOST
POST http://localhost:8084/importer/localities/{countyName}
Content-Type: application/json

{
  "localities": [
    {
      "name": "STALOWA WOLA",
      "longitude": 22.0499998,
      "latitude": 50.5666644
    },
    {
      "name": "JASTKOWICE",
      "longitude": 22.10667,
      "latitude": 50.60389
    }
  ]
}

###

# MICROSERVICES
POST http://{eureka-server-address}:8084/importer/localities/{countyName}
Content-Type: application/json

{
  "localities": [
    {
      "name": "STALOWA WOLA",
      "longitude": 22.0499998,
      "latitude": 50.5666644
    },
    {
      "name": "JASTKOWICE",
      "longitude": 22.10667,
      "latitude": 50.60389
    }
  ]
}

###