# LOCALHOST
GET http://localhost:8083/localities
Content-Type: application/json

{
  "voivodeshipName": "PODKARPACKIE",
  "countyName": "STALOWOWOLSKI",
  "localityName": "STALOWA WOLA",
  "radius": 60
}

###

# MICROSERVICES
GET http://172.18.0.8:8083/localities
Content-Type: application/json

{
  "voivodeshipName": "PODKARPACKIE",
  "countyName": "STALOWOWOLSKI",
  "localityName": "STALOWA WOLA",
  "radius": 60
}

###