version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb

  otomoto-service:
    image: otomoto-service
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - /data/otomoto-service

  otomoto-client:
    image: otomoto-client
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - otomoto-service
    ports:
      - 8081:8081
    volumes:
      - /data/otomoto-client

  currency-api:
    image: currency-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
#    depends_on:
#      - mongodb
    ports:
      - 8082:8082
    volumes:
      - /data/currency-api

  location-api:
    image: location-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8083:8083
    volumes:
      - /data/location-api

  data-importer:
    image: data-importer
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8084:8084
    volumes:
      - /data/data-importer