spring:
  application:
    name: api-gateway

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api
  host:
    connect-timeout-millis: 30000