server:
  port: 8081

spring:
  application:
    name: otomoto-client
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root:
      info
    org:
      springframework: info