server:
  port: 8081

spring:
  application:
    name: otomoto-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root:
      OFF
    org:
      springframework: OFF