server:
  port: 8082

spring:
  application:
    name: currency-api

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
    org:
      springframework: info

exchange-api-url: https://api.exchangeratesapi.io/latest