# DELETE ALL VEHICLES

# LOCALHOST
DELETE http://localhost:8081/vehicles/all

###

# MICROSERVICES
DELETE http://{eureka-server-address}:8081/vehicles/all

###

# DELETE VEHICLE BY ID

# LOCALHOST
DELETE http://localhost:8081/vehicles?vehicleId={vehicleId}

###

# MICROSERVICES
DELETE http://{eureka-server-address}:8081/vehicles?vehicleId={vehicleId}

###