# DELETE ALL VEHICLES

# LOCALHOST
DELETE http://localhost:8081/vehicles/all

###

# MICROSERVICES
DELETE http://172.18.0.6:8081/vehicles/all

###

# DELETE VEHICLE BY ID

# LOCALHOST
DELETE http://localhost:8081/vehicles?vehicleId={vehicleId}

###

# MICROSERVICES
DELETE http://172.18.0.6:8081/vehicles?vehicleId={vehicleId}

###