# GET ALL VEHICLES

# LOCALHOST
GET http://localhost:8081/vehicles/all

###

# MICROSERVICES
GET http://{eureka-server-address}:8081/vehicles/all

###

# GET VEHICLE BY ID

# LOCALHOST
GET http://localhost:8081/vehicles?vehicleId={vehicleId}

###

# MICROSERVICES
GET http://{eureka-server-address}:8081/vehicles?vehicleId={vehicleId}

###