# GET ALL VEHICLES

# LOCALHOST
GET http://localhost:8081/vehicles/all

###

# MICROSERVICES
GET http://172.18.0.6:8081/vehicles/all

###

# GET VEHICLE BY ID

# LOCALHOST
GET http://localhost:8081/vehicles?vehicleId={vehicleId}

###

# MICROSERVICES
GET http://172.18.0.6:8081/vehicles?vehicleId={vehicleId}

###