# GET ALL VEHICLES

# LOCALHOST
GET http://localhost:8080/vehicles/all

###

# MICROSERVICES
GET http://172.18.0.5:8080/vehicles/all

###

# GET VEHICLE BY ID

# LOCALHOST
GET http://localhost:8080/vehicles?vehicleId={vehicleId}

###

# MICROSERVICES
GET http://172.18.0.5:8080/vehicles?vehicleId={vehicleId}

###
